version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DROOM_WEATHER_API_BASE_URL: https://thirdparty-weather-api-v2.droom.workers.dev
      DROOM_API_KEY: CMRJW4WT7V3QA5AOIGPBC
      TIMEOUT_SECONDS: 1.49
    volumes:
      - ./src:/src
      - ./tests:/tests
